### PR TITLE
checkout Jw-edit 

### PR DESCRIPTION
**Pull request by JustinWarden**
tasks section
user should be able to add task
user should be able to edit task
user should click complete to delete task
the tasks page should update for each

### CODE REVIEW

**Comment by kelli-evans09** [comment]
When you click the "completed" checkbox, the whole list of tasks disappear instead of just the one task

**Comment by Jengwen** [comment]
When you click completed on original tasks they delete all.  When you create, edit, or complete tasks the complete check mark works correctly

**Comment by Jengwen** [comment]
tasks are now editing, creating, and deleting properly

**Comment by LukeAMiller** [comment]
take it to the limit one more time

**Comment by kelli-evans09** [comment]
Works great without the preloaded data!

**Pull request merged**
